# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "SSS&SDS Group"
description: > # this means to ignore newlines until "baseurl:"
  SSS&SDS is a academic group in Huazhong University of Science and Technology.
baseurl: ""
url: "https://ssssds.github.io"
permalink: /:year/:month/:day/:title
paginate: 8
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
# MatJek specific configurations
github_profile: "https://github.com/SSSSDS/ssssds.github.io"
user: "SSS&SDS group"
user_email: "academic pages for SSS&SDS group"
#contact_url: "https://goo.gl/tVljbV"
#google_tracking_id: "UA-96359860-1"
#google_site_verification: "UA-96359860-1"
disqus_shortname: "matjek"

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
collections:
  project:
    output: true
    permalink: /:collection/:path
defaults:
  - scope:
      path: "assets/proimg"
    values:
      image: true
sass:
  style: compressed
future: true
